  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web-service
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`web.localhost`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
    volumes:
      - web_data:/usr/share/nginx/html:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount a custom Nginx configuration file
    networks:
      - proxy
    environment:
      - NGINX_HOST=web.localhost
    depends_on:
      - traefik