http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
  routers:
    default-redirect:
      rule: "HostRegexp(`{host:.+}`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop
  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"